name: kollection
description: "A simple gallery app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+2
  path: ^1.9.1
  image_picker: ^1.1.0
  file_selector: ^1.1.0
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  flutter_font_picker: ^2.0.0
  file_selector_android: ^0.5.2+4
  file_selector_linux: ^0.9.4
  file_selector_windows: ^0.9.3+5
  flutter_colorpicker: ^1.1.0
  flex_color_picker: ^3.8.0
  image: ^4.7.2
  file_picker: ^10.3.10
  permission_handler: ^12.0.1
  uuid: ^4.5.2
  flutter_staggered_grid_view: ^0.7.0
  image_cropper: ^11.0.0
  crop_your_image: ^2.0.0
  platform_detail: ^5.1.0
  flutter_iconpicker: ^4.0.3
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  omni_datetime_picker: ^2.3.1
  sticky_headers: ^0.3.0+2
  shared_preferences: ^2.5.5
  timeago: ^3.2.2
  table_calendar: ^3.2.1
  dynamic_color: ^1.9.0
  window_manager: ^0.5.1
  photo_manager: ^3.8.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_launcher_icons:
  android: true
  ios: false
  remove_alpha_ios: true
  image_path: assets/images/icon/ic_launcher.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/images/icon/ic_launcher.png
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: assets/images/icon/ic_launcher.png
    icon_size: 48
  linux:
    generate: true
    image_path: assets/images/icon/ic_launcher.png
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icon/
    - assets/fonts/
    - assets/audio/argon.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Wolland
      fonts:
        - asset: assets/fonts/Wolland.ttf
    - family: Staatliches
      fonts:
        - asset: assets/fonts/Staatliches.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
          weight: 100
          style: normal

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic

    - family: Lunasima
      fonts:
        - asset: assets/fonts/Lunasima/Lunasima-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lunasima/Lunasima-Regular.ttf
          weight: 400

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
          weight: 100
          style: normal

    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-VariableFont_wdth,wght.ttf
          weight: 100
          style: normal

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-VariableFont_wdth,wght.ttf
          weight: 100
          style: normal

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-VariableFont_wdth,wght.ttf
          weight: 100
          style: normal
msix_config:
  display_name: Kollection
  logo_path: assets/ic_launcher.png
  trim_logo: false